CREATE TABLE Photos
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	TimeMaking DATETIME,
	TimeLoad DATETIME NOT NULL,
	Name NCHAR(100) NOT NULL,
	CommentUser NCHAR(3000),
	Model NCHAR(200),
	GPSlat REAL,
	GPSlon REAL,
	AlbumID INT NOT NULL,
	AlbumQueue INT,
	FilePhoto VARBINARY(8000) NOT NULL,
	GUID NCHAR(100)
)

CREATE TABLE Albums
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	UserID INT  NOT NULL,
	Name NCHAR(100) NOT NULL,
	Description NCHAR(3000),
	GUID NCHAR(100)
)

CREATE TABLE Users
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	Email NCHAR(100),
	FirstName NCHAR(100),
	SecondName NCHAR(100), 
	ThirdName NCHAR(100),
	BirthDate DATE,
	Description NCHAR(3000),
	Role NCHAR(5)
)

CREATE TABLE Comments
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	UserID INT NOT NULL,
	PhotoID INT NOT NULL,
	Text NCHAR(3000) NOT NULL
)

CREATE TABLE PrivateDatas
(
	UserID INT,
	Password NCHAR(50) NOT NULL
)

ALTER TABLE Albums ADD CONSTRAINT AlbumsUserID FOREIGN KEY (UserID) REFERENCES Users(ID); 
ALTER TABLE Comments ADD CONSTRAINT CommUserID FOREIGN KEY (UserID) REFERENCES Users(ID); 
ALTER TABLE Comments ADD CONSTRAINT CommPhotoID FOREIGN KEY  (PhotoID)  REFERENCES Photos(ID); 
ALTER TABLE Photos ADD CONSTRAINT PhotosAlbumIS FOREIGN KEY (AlbumID) REFERENCES Albums(ID); 
ALTER TABLE PrivateDatas ADD CONSTRAINT PrivateDataUserID FOREIGN KEY (UserID) REFERENCES Users(ID); 
ALTER TABLE PrivateDatas ADD CONSTRAINT UniquePrivateDataID UNIQUE(UserID);